#!/usr/bin/env bun

/**
 * Script to create source code submission zip for Firefox Add-ons
 * This includes all source code and build instructions but excludes build artifacts
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { $ } from "bun";

const projectRoot = join(import.meta.dir, "..");

// Get version from package.json
const packageJsonPath = join(projectRoot, "packages/extension/package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const version = packageJson.version;

const outputDir = join(projectRoot, "packages/extension/.output");
const outputFile = `tabcanopy-${version}-source.zip`;
const outputPath = join(outputDir, outputFile);

console.log(`📦 Creating source submission zip for Tab Canopy v${version}...`);
console.log("");

// Build and zip extension to generate WXT's sources.zip
console.log("🔨 Building Firefox extension to generate WXT sources.zip...");
await $`cd ${projectRoot} && bun run zip:firefox`.quiet();
console.log("✓ Extension built");
console.log("");

// Create temporary directory for staging
const tempDir = await $`mktemp -d`.text();
const stagingDir = join(tempDir.trim(), "tabcanopy-source");

console.log("📋 Copying source files...");

// Create staging directory
await $`mkdir -p ${stagingDir}`;

// Copy root files
const rootFiles = [
	"package.json",
	"bun.lock",
	"turbo.json",
	"tsconfig.json",
	"biome.json",
	"LICENSE",
	"README.md",
	"SOURCE_BUILD_README.md",
];

for (const file of rootFiles) {
	const srcPath = join(projectRoot, file);
	if (existsSync(srcPath)) {
		await $`cp ${srcPath} ${stagingDir}/`;
	}
}

// Copy packages (excluding build artifacts and dependencies)
await $`mkdir -p ${join(stagingDir, "packages")}`;

// Extension package
console.log("  → packages/extension/");
await $`mkdir -p ${join(stagingDir, "packages/extension")}`;
await $`rsync -a \
  --exclude='node_modules' \
  --exclude='.output' \
  --exclude='dist' \
  --exclude='.turbo' \
  --exclude='.wxt' \
  --exclude='*.log' \
  ${join(projectRoot, "packages/extension")}/ \
  ${join(stagingDir, "packages/extension")}/`;

// E2E tests package (for completeness, not needed for build)
console.log("  → packages/e2e-tests/");
await $`mkdir -p ${join(stagingDir, "packages/e2e-tests")}`;
await $`rsync -a \
  --exclude='node_modules' \
  --exclude='playwright-report' \
  --exclude='test-results' \
  --exclude='.turbo' \
  --exclude='*.log' \
  ${join(projectRoot, "packages/e2e-tests")}/ \
  ${join(stagingDir, "packages/e2e-tests")}/`;

// Copy scripts directory
console.log("  → scripts/");
await $`mkdir -p ${join(stagingDir, "scripts")}`;
const scriptsDir = join(projectRoot, "scripts");
if (existsSync(scriptsDir)) {
	await $`cp ${join(scriptsDir, "*.ts")} ${join(stagingDir, "scripts")}/ 2>/dev/null || true`.nothrow();
}

// Copy docs (excluding large media files)
console.log("  → docs/");
await $`mkdir -p ${join(stagingDir, "docs")}`;
const docsDir = join(projectRoot, "docs");
if (existsSync(docsDir)) {
	await $`rsync -a \
    --exclude='*.mp4' \
    --exclude='*.mov' \
    --exclude='*.webm' \
    ${docsDir}/ \
    ${join(stagingDir, "docs")}/ 2>/dev/null || true`.nothrow();
}

// Copy WXT's auto-generated sources.zip
console.log("  → WXT sources.zip (auto-generated by build)");
const wxtSourcesZip = join(
	projectRoot,
	"packages/extension/.output",
	`tabcanopyextension-${version}-sources.zip`,
);
if (existsSync(wxtSourcesZip)) {
	await $`cp ${wxtSourcesZip} ${stagingDir}/`;
	console.log("    ✓ Included WXT's sources.zip for reference");
} else {
	console.log(
		"    ⚠ WXT sources.zip not found (this shouldn't happen after build)",
	);
}

// Create the zip
console.log("");
console.log("🔨 Creating zip archive...");
await $`cd ${tempDir.trim()} && zip -r ${outputPath} tabcanopy-source -q`;

// Cleanup
await $`rm -rf ${tempDir.trim()}`;

console.log("");
console.log("✅ Source submission package created successfully!");
console.log("");
console.log(`📁 Output file: packages/extension/.output/${outputFile}`);

// Get file size
if (existsSync(outputPath)) {
	const sizeOutput = await $`du -h ${outputPath}`.text();
	const size = sizeOutput.trim().split("\t")[0];
	console.log(`📊 File size: ${size}`);
}

console.log("");
console.log("📋 Contents included:");
console.log("   ✓ All source code (full monorepo)");
console.log("   ✓ Build configuration files");
console.log("   ✓ Package lockfile (bun.lock)");
console.log("   ✓ Build instructions (SOURCE_BUILD_README.md)");
console.log("   ✓ License and documentation");
console.log("   ✓ WXT's auto-generated sources.zip (extension package only)");
console.log("");
console.log("❌ Excluded (will be generated during build):");
console.log("   ✗ node_modules/");
console.log("   ✗ .output/ (except sources.zip)");
console.log("   ✗ Build artifacts");
console.log("   ✗ Large media files (*.mp4, *.mov, *.webm)");
console.log("");
console.log("📤 Upload this file to Firefox Add-ons submission:");
console.log(`   packages/extension/.output/${outputFile}`);
console.log("");
